### PR TITLE
Remove git dependency on gemspec.

### PR DESCRIPTION
**Pull request by jsmpereira**

### CODE REVIEW

**Comment by ct-clearhaus** [comment]
Failing specs?

**Comment by jsmpereira** [comment]
I blame `aws-sdk` :stuck_out_tongue: 

The v2 SDK took over the gem name and actually uses a different namespace, `Aws` iirc (as opposed to the v1 `AWS`).

So we need to update the sdk dependency to either `aws-sdk-v1` or `'aws-sdk', '< 2'`.

https://github.com/aws/aws-sdk-ruby/tree/aws-sdk-v1#installation

**Comment by ct-clearhaus** [comment]
Darn, aws-sdk.
:+1:

**Comment by jsmpereira** [comment]
@ct-clearhaus quick :eyes: ?

**Comment by ct-clearhaus** [comment]
:+1:

**Pull request merged**
